---
title: "TITLE TK"
author: "Zoya Azhar, Ruby Wu, Ruth Tekleab Mekbib"
date: "April 8, 2019"
output:
  html_document:
    code_folding: hide
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(macleish)
library(sf)
```

-title
-problem statement
-500-800 words
-explain the points(visual mapping) i.e. they are intersection points
-shenandoah (external analysis point)
-actionable recommendation
-resource discussion (signage, posters)

-chunks, line breaks, comment proofread

```{r message=FALSE, warning=FALSE}

# compute lengths for trails

lengths <- macleish_layers %>%
  pluck("trails") %>%
  st_length()

# create dataframe with lengths and get rid of non-trails

trails <- macleish_layers[["trails"]] %>%
  mutate(lengths = lengths) %>%
  filter(color != "") %>%
  filter(color != "Road")

# one trail's color was missing (as assigned by the official Macleish trail map)
  
trails$color <- as.character(trails$color)
trails[7,2] = "Green"
trails$color <- as.factor(trails$color)


# create dataframe with sum of lengths and total elevation change

# contains lengths 

initial <- trails %>%
  st_intersection(pluck(macleish_layers,"contours_3m")) %>%
  group_by(name,lengths) %>%
  summarise(segments = n(), elev_change = (max(ELEV_M)-min(ELEV_M)))

# contains total elevation change and total length of each trail

initial2 <- initial %>%
  group_by(name) %>%
  summarise(total_length = sum(lengths), elev_change = sum(elev_change), segments = sum(segments))

# can compute difficulty level using sqrt((elevation_gain)*2*(distance)), Shenandoah rating

final <- initial2 %>%
  mutate(difficulty = sqrt(as.numeric(((elev_change) *2* (total_length))))) %>%
  arrange(difficulty)

# plot 

ggplot() + 
  geom_sf(data = macleish_layers[["trails"]],
          color = "black", size = 1, alpha = 0.2) + 
  geom_sf(data = macleish_layers[["contours_3m"]]) +
  geom_sf(data = final, aes(fill = name, color = name)) +
  geom_sf_label(data = final, aes(label = elev_change)) +
  labs(title = "Total elevation change over each Macleish trail (meters)") +
  labs(x = "Latitude") +
  labs(y = "Longitude")
  

# plot elevation change on each trail

# ENTRY TRAIL / GREEN
entrytrail <- trails %>%
  st_intersection(pluck(macleish_layers,"contours_3m")) %>%
  filter(name == "entry trail") %>%
  arrange(name) %>%
  mutate(elev_change = ELEV_M-lag(ELEV_M))

entry_trail_plot <- ggplot(entrytrail,aes(x = ELEV_M, y = elev_change)) +
  geom_line()
entry_trail_plot

# WESTERN TRAIL / RED 
westernloop <- trails %>%
  st_intersection(pluck(macleish_layers,"contours_3m")) %>%
  filter(name == "Western Loop") %>%
  arrange(name) %>%
  mutate(elev_change = ELEV_M-lag(ELEV_M))

westernloop_plot <- ggplot(westernloop,aes(x = ELEV_M, y = elev_change)) +
  geom_line()
westernloop_plot

# EASTERN LOOP / BLUE
easternloop <- trails %>%
  st_intersection(pluck(macleish_layers,"contours_3m")) %>%
  filter(name == "Eastern Loop") %>%
  mutate(elev_change = ELEV_M-lag(ELEV_M))

easternloop_plot <- ggplot(easternloop,aes(x = ELEV_M, y = elev_change)) +
  geom_line()
easternloop_plot


# PORCUPINE TRAIL / WHITE
porcupinetrail <- trails %>%
  st_intersection(pluck(macleish_layers,"contours_3m")) %>%
  filter(name == "Porcupine Trail") %>%
  arrange(name) %>%
  mutate(elev_change = ELEV_M-lag(ELEV_M))

porcupinetrail_plot <- ggplot(porcupinetrail,aes(x = ELEV_M, y = elev_change)) +
  geom_line()
porcupinetrail_plot

# VERNAL POOL LOOP / YELLOW
vernalpoolloop <- trails %>%
  st_intersection(pluck(macleish_layers,"contours_3m")) %>%
  filter(name == "Vernal Pool Loop") %>%
  mutate(elev_change = ELEV_M-lag(ELEV_M))

vernalpool_plot <- ggplot(vernalpoolloop,aes(x = ELEV_M, y = elev_change)) +
  geom_line()
vernalpool_plot


```
  
  
**Footnotes:**

GitHub repository:

https://github.com/zazharr/mp3

https://github.com/zazharr/mp3.git

***

